

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 580)
        MainWindow.setMinimumSize(QtCore.QSize(400, 580))
        MainWindow.setMaximumSize(QtCore.QSize(400, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sonuc = QtWidgets.QLabel(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(0, 10, 391, 91))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.sonuc.setFont(font)
        self.sonuc.setStyleSheet("color: rgb(0, 0, 255);")
        self.sonuc.setFrameShape(QtWidgets.QFrame.Box)
        self.sonuc.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sonuc.setLineWidth(2)
        self.sonuc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sonuc.setObjectName("sonuc")
        self.yuzde = QtWidgets.QPushButton(self.centralwidget)
        self.yuzde.setGeometry(QtCore.QRect(0, 110, 95, 70))
        self.yuzde.setMinimumSize(QtCore.QSize(95, 70))
        self.yuzde.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.yuzde.setFont(font)
        self.yuzde.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.yuzde.setObjectName("yuzde")
        self.silme = QtWidgets.QPushButton(self.centralwidget)
        self.silme.setGeometry(QtCore.QRect(100, 110, 95, 70))
        self.silme.setMinimumSize(QtCore.QSize(95, 70))
        self.silme.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.silme.setFont(font)
        self.silme.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.silme.setObjectName("silme")
        self.geri = QtWidgets.QPushButton(self.centralwidget)
        self.geri.setGeometry(QtCore.QRect(200, 110, 95, 70))
        self.geri.setMinimumSize(QtCore.QSize(95, 70))
        self.geri.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.geri.setFont(font)
        self.geri.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.geri.setObjectName("geri")
        self.bolme = QtWidgets.QPushButton(self.centralwidget)
        self.bolme.setGeometry(QtCore.QRect(300, 110, 95, 70))
        self.bolme.setMinimumSize(QtCore.QSize(95, 70))
        self.bolme.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.bolme.setFont(font)
        self.bolme.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bolme.setObjectName("bolme")
        self.bir = QtWidgets.QPushButton(self.centralwidget)
        self.bir.setGeometry(QtCore.QRect(0, 380, 95, 70))
        self.bir.setMinimumSize(QtCore.QSize(95, 70))
        self.bir.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.bir.setFont(font)
        self.bir.setObjectName("bir")
        self.dort = QtWidgets.QPushButton(self.centralwidget)
        self.dort.setGeometry(QtCore.QRect(0, 290, 95, 70))
        self.dort.setMinimumSize(QtCore.QSize(95, 70))
        self.dort.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.dort.setFont(font)
        self.dort.setObjectName("dort")
        self.yedi = QtWidgets.QPushButton(self.centralwidget)
        self.yedi.setGeometry(QtCore.QRect(0, 200, 95, 70))
        self.yedi.setMinimumSize(QtCore.QSize(95, 70))
        self.yedi.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.yedi.setFont(font)
        self.yedi.setObjectName("yedi")
        self.isaret = QtWidgets.QPushButton(self.centralwidget)
        self.isaret.setGeometry(QtCore.QRect(0, 470, 95, 70))
        self.isaret.setMinimumSize(QtCore.QSize(95, 70))
        self.isaret.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.isaret.setFont(font)
        self.isaret.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.isaret.setObjectName("isaret")
        self.iki = QtWidgets.QPushButton(self.centralwidget)
        self.iki.setGeometry(QtCore.QRect(100, 380, 95, 70))
        self.iki.setMinimumSize(QtCore.QSize(95, 70))
        self.iki.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.iki.setFont(font)
        self.iki.setObjectName("iki")
        self.sekiz = QtWidgets.QPushButton(self.centralwidget)
        self.sekiz.setGeometry(QtCore.QRect(100, 200, 95, 70))
        self.sekiz.setMinimumSize(QtCore.QSize(95, 70))
        self.sekiz.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.sekiz.setFont(font)
        self.sekiz.setObjectName("sekiz")
        self.bes = QtWidgets.QPushButton(self.centralwidget)
        self.bes.setGeometry(QtCore.QRect(100, 290, 95, 70))
        self.bes.setMinimumSize(QtCore.QSize(95, 70))
        self.bes.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.bes.setFont(font)
        self.bes.setObjectName("bes")
        self.sifir = QtWidgets.QPushButton(self.centralwidget)
        self.sifir.setGeometry(QtCore.QRect(100, 470, 95, 70))
        self.sifir.setMinimumSize(QtCore.QSize(95, 70))
        self.sifir.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.sifir.setFont(font)
        self.sifir.setObjectName("sifir")
        self.uc = QtWidgets.QPushButton(self.centralwidget)
        self.uc.setGeometry(QtCore.QRect(200, 380, 95, 70))
        self.uc.setMinimumSize(QtCore.QSize(95, 70))
        self.uc.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.uc.setFont(font)
        self.uc.setObjectName("uc")
        self.dokuz = QtWidgets.QPushButton(self.centralwidget)
        self.dokuz.setGeometry(QtCore.QRect(200, 200, 95, 70))
        self.dokuz.setMinimumSize(QtCore.QSize(95, 70))
        self.dokuz.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.dokuz.setFont(font)
        self.dokuz.setObjectName("dokuz")
        self.alti = QtWidgets.QPushButton(self.centralwidget)
        self.alti.setGeometry(QtCore.QRect(200, 290, 95, 70))
        self.alti.setMinimumSize(QtCore.QSize(95, 70))
        self.alti.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.alti.setFont(font)
        self.alti.setObjectName("alti")
        self.cikarma = QtWidgets.QPushButton(self.centralwidget)
        self.cikarma.setGeometry(QtCore.QRect(300, 290, 95, 70))
        self.cikarma.setMinimumSize(QtCore.QSize(95, 70))
        self.cikarma.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.cikarma.setFont(font)
        self.cikarma.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cikarma.setObjectName("cikarma")
        self.toplama = QtWidgets.QPushButton(self.centralwidget)
        self.toplama.setGeometry(QtCore.QRect(300, 380, 95, 70))
        self.toplama.setMinimumSize(QtCore.QSize(95, 70))
        self.toplama.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.toplama.setFont(font)
        self.toplama.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toplama.setObjectName("toplama")
        self.esittir = QtWidgets.QPushButton(self.centralwidget)
        self.esittir.setGeometry(QtCore.QRect(300, 470, 95, 70))
        self.esittir.setMinimumSize(QtCore.QSize(95, 70))
        self.esittir.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.esittir.setFont(font)
        self.esittir.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.esittir.setObjectName("esittir")
        self.carpma = QtWidgets.QPushButton(self.centralwidget)
        self.carpma.setGeometry(QtCore.QRect(300, 200, 95, 70))
        self.carpma.setMinimumSize(QtCore.QSize(95, 70))
        self.carpma.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.carpma.setFont(font)
        self.carpma.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carpma.setObjectName("carpma")
        self.nokta = QtWidgets.QPushButton(self.centralwidget)
        self.nokta.setGeometry(QtCore.QRect(200, 470, 95, 70))
        self.nokta.setMinimumSize(QtCore.QSize(95, 70))
        self.nokta.setMaximumSize(QtCore.QSize(95, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(26)
        self.nokta.setFont(font)
        self.nokta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nokta.setObjectName("nokta")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hesap Makinesi"))
        self.sonuc.setText(_translate("MainWindow", "0"))
        self.yuzde.setText(_translate("MainWindow", "%"))
        self.silme.setText(_translate("MainWindow", "C"))
        self.geri.setText(_translate("MainWindow", "←"))
        self.bolme.setText(_translate("MainWindow", "/"))
        self.bir.setText(_translate("MainWindow", "1"))
        self.dort.setText(_translate("MainWindow", "4"))
        self.yedi.setText(_translate("MainWindow", "7"))
        self.isaret.setText(_translate("MainWindow", "+/-"))
        self.iki.setText(_translate("MainWindow", "2"))
        self.sekiz.setText(_translate("MainWindow", "8"))
        self.bes.setText(_translate("MainWindow", "5"))
        self.sifir.setText(_translate("MainWindow", "0"))
        self.uc.setText(_translate("MainWindow", "3"))
        self.dokuz.setText(_translate("MainWindow", "9"))
        self.alti.setText(_translate("MainWindow", "6"))
        self.cikarma.setText(_translate("MainWindow", "-"))
        self.toplama.setText(_translate("MainWindow", "+"))
        self.esittir.setText(_translate("MainWindow", "="))
        self.carpma.setText(_translate("MainWindow", "X"))
        self.nokta.setText(_translate("MainWindow", "."))
